FROM node:8.11-alpine as build-stage

WORKDIR /app
COPY . /app

RUN npm install -g @angular/cli@7.0.6 && npm install
#RUN ng build --prod --aot
ARG configuration=production
RUN npm run build -- --output-path=./dist/out --configuration $configuration

FROM nginx:1.15-alpine
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist/out /usr/share/nginx/html

EXPOSE 4200
